export const routeTitles: Record<string, string> = {
  "/": "Dashboard",
  "/dashboard-overview-2": "Dashboard Overview 2",
  "/calendar": "Calendar",
  "/chat": "Chat",
  "/inbox": "Inbox",
  "/email-detail": "Email Detail",
  "/compose": "Compose",
  "/products": "Products",
  "/product-detail": "Product Detail",
  "/orders": "Orders",
  "/order-detail": "Order Detail",
  "/file-manager": "File Manager",
  "/profile": "Profile",
  "/pricing": "Pricing",
  "/invoice": "Invoice",
  "/faq": "FAQ",
  "/timeline": "Timeline",
  "/crud-data-list": "CRUD Data List",
  "/crud-form": "CRUD Form",
  "/wizard-layout-1": "Wizard Layout 1",
  "/wizard-layout-2": "Wizard Layout 2",
  "/wizard-layout-3": "Wizard Layout 3",
  "/regular-table": "Regular Table",
  "/tabulator": "Tabulator",
  "/modal": "Modal",
  "/slideover": "Slideover",
  "/notification": "Notification",
  "/tab": "Tab",
  "/accordion": "Accordion",
  "/button": "Button",
  "/alert": "Alert",
  "/progress-bar": "Progress Bar",
  "/tooltip": "Tooltip",
  "/dropdown": "Dropdown",
  "/typography": "Typography",
  "/icon": "Icon",
  "/loading-icon": "Loading Icon",
  "/regular-form": "Regular Form",
  "/datepicker": "Datepicker",
  "/tom-select": "Tom Select",
  "/file-upload": "File Upload",
  "/wysiwyg-editor": "WYSIWYG Editor",
  "/validation": "Validation",
  "/chart": "Chart",
  "/slider": "Slider",
  "/image-zoom": "Image Zoom",
};
